### PR TITLE
Fix profile #112

### PR DESCRIPTION
**Pull request by louisifn**
#112 Fixes, some code neatening, fixes for deleted posts & some design improvements

### CODE REVIEW

**Comment by nathanbillis** [comment]
@louisifn could you either rebase or merge the master please - there’s a few conflicts and I’m not sure what’s the best way to resolve the all

**Comment by louisifn** [comment]
Will do

**Comment by profjb58** [comment]
Am I ok to append to this branch and finish it as well Louis. Need to update the privacy collections really with the new privacy stuff and get rid of some unused code.

**Comment by louisifn** [comment]
@profjb58  yeah mate will just push the pull from master

**Comment by louisifn** [comment]
added a fix for all post deletion, there was an error in logic. Recipes on profiles on click has been disabled accidentally in one of the merges so this was readded

**Comment by profjb58** [comment]
Fixed pretty much everything except for the issue where it crashes between switching to the image tab on another persons profile. I need to re-write tests for this since i've added new functionality and modified some that currently exists. ETA should be tommorow.

**Comment by louisifn** [comment]
#122 and #95 both fixed

**Comment by louisifn** [comment]
@profjb58 can you make it so it auto loads on the private tab, please

**Comment by louisifn** [comment]
it would appear that the issue " switching to the image tab on another persons profile" has been added from your push to this branch

**Pull request merged**
