### PR TITLE
C17 newversion

### PR DESCRIPTION
**Pull request by Jun0305**

### CODE REVIEW

**Comment by profjb58** [comment]
Results for Breakfast compared to dinner/lunch are different so it does seem to be filtering based on the type of recipe which is good. The Top picks scrollview needs to be left as is really though.

**Comment by nathanbillis** [comment]
[C17 - **Enable Meal Planner** As a user, I want to be able to select a time frame to see certain recipes, such as breakfast, lunch or dinner](https://trello.com/c/Ntsv5G1u/37-c17-enable-meal-planner-as-a-user-i-want-to-be-able-to-select-a-time-frame-to-see-certain-recipes-such-as-breakfast-lunch-or-din)

**Comment by profjb58** [comment]
Works perfectly. Results are filtered properly. I manually tested by changing boolean values for lunch, dinner and breakfast stuff and it all updated properly. Good job.

**Comment by profjb58** [comment]
Completed test reports. Also rebased properly. Should be ready to merge now.

**Pull request merged**
