### PR TITLE
C5  shopping

### PR DESCRIPTION
**Pull request by becky219**
all testing done. should be good to go.

Having some issues resolving a few conflicts with the master, its saying I don't have permission to access some. There shouldn't be too many thought I only recently updated it

### CODE REVIEW

**Comment by profjb58** [comment]
I'm not sure the rebase worked which is a bit weird.
Certain xml files have also been deleted which is again a bit strange. It might take quite a while to resolve this so the quicker we can get onto merging this probably the better.

**Comment by nathanbillis** [comment]
Not going to rebase this - it's so old, going to try and merge master (35 file conflicts) then have a look

**Comment by nathanbillis** [comment]
The branch is from 15/3/20 and last had some of the master merged 24/4/20

**Comment by nathanbillis** [comment]
[C5 - **Enable Meal Planner** As a user who has a lot of store cupboard ingredients I can tap what ingredients I need to add to a shopping list so I can build a shopping list based on the recipes without including ingredients I already have](https://trello.com/c/JxyZWXwH/25-c5-enable-meal-planner-as-a-user-who-has-a-lot-of-store-cupboard-ingredients-i-can-tap-what-ingredients-i-need-to-add-to-a-shopp)

**Pull request merged**
