### PR TITLE
profile fixes

### PR DESCRIPTION
**Pull request by profjb58**
**Fixed**
- Profile image not updating
- Username from usernames collection not getting deleted when a user deletes there profile
- Fixed private profile visibility switch not staying retained
- About me now displays nothing if blank
- About me box now expands when typing

### CODE REVIEW

**Comment by nathanbillis** [comment]
fixes #118 and fixes #109

**Comment by louisifn** [comment]
I'm unable to run this branch, keeps crashing when trying to enter profile
Screenshot 2020-05-29 at 21 17 44

**Comment by profjb58** [comment]
> 
> 
> I'm unable to run this branch, keeps crashing when trying to enter profile
> Screenshot 2020-05-29 at 21 17 44

Fixed it. I had left some code in for the red banner I forgot to get rid of.

**Comment by louisifn** [comment]
Rgr, will have a look through tomorrow, night

**Pull request merged**
