### PR TITLE
B1 refactor

### PR DESCRIPTION
**Pull request by jamesclawley**
Adds a new class for presentation slides to reduce load on the presentation class

### CODE REVIEW

**Comment by profjb58** [comment]
So there are some issues with the recent mealplanner merge that means I can't really test it.
For this reason it makes sense to wait until the mealplanner is fixed before doing this.
If someone can immediately re-open the mealplanner branch that would be handy. Thanks.

**Comment by nathanbillis** [comment]
> So there are some issues with the recent mealplanner merge that means I can't really test it.
> For this reason it makes sense to wait until the mealplanner is fixed before doing this.
> If someone can immediately re-open the mealplanner branch that would be handy. Thanks.

Make a new branch and work on the bug fixes, what are the issues with meal planner?

**Comment by nathanbillis** [comment]
> For this reason it makes sense to wait until the mealplanner is fixed before doing this.
What would make sense would be to merge this, then open a new branch from the head of this and work on the fixes for the meal planner.

**Comment by profjb58** [comment]
True. I'd say with this branch re-opened though it might make sense to write some tests for it whilst we can to make sure we don't run into issues further down the line. This will involve me re-opening my own branch for audio and timers but it's probably worth it. Obviously takes more time though.

Just discovered a 'testBaconComment' thing has been added which essentially allows us to navigate to specific recipes to test. No idea who wrote it though.

**Comment by profjb58** [comment]
Also kudos to James to refactoring tho and comments. A lot easier to understand now.

**Comment by nathanbillis** [comment]
I'm going to merge this, then we can create new branches for the audio & timers and for any other issues we find later on. 

We shouldn't be reopening new branches once they're merged into the master because it will cause alot of issues later on. If there's something forgotten or needs changing later on then a new branch should be made with a new PR when its finished.

**Comment by nathanbillis** [comment]
Merging and closing this branch, any new issues found after basic troubleshooting should be opened and new branches made,

**Pull request merged**
