### PR TITLE
Design changes

### PR DESCRIPTION
**Pull request by profjb58**
Lots of design changes, mainly colours. It isn't perfect by any means but I think it's an improvement over before.
Happy with everything except the profile page and I can't find where to change the background colour for reviews.

There is a very fine line between the app looking like the inside of a hospital and an app that people would enjoy looking at.

Took inspiration from the trainline app and the simply vegan app on IOS.
My phone is pretty old and cheap and so is my monitor so the colours compared to for e.g. the ipad i'm referencing for simply vegan are quite muted.

Might be worth changing the action colour back to purple, still think that looks better but mute the colour a bit more so it isn't as intense.

### CODE REVIEW

**Comment by profjb58** [comment]
Screenshot_20200602-012252_Scran Plan
Screenshot_20200602-012256_Scran Plan
Screenshot_20200602-012303_Scran Plan
Screenshot_20200602-012313_Scran Plan
Screenshot_20200602-012236_Scran Plan
Screenshot_20200602-012239_Scran Plan
Screenshot_20200602-012243_Scran Plan

**Comment by profjb58** [comment]
Gonna change the tab selectors to white i think. Should make it look a bit better.

**Comment by louisifn** [comment]
I'm not sure I like the dark grey register button, there is also a 'back to register' button that should be the same colour as register but is still blue. I do prefer the blue to the grey though.

**Comment by louisifn** [comment]
In creating a post on the feed you have disabled the centering of the rating bar somehow, now aligns to the left, I'm not a fan

**Comment by louisifn** [comment]
Other than those i like it

**Comment by profjb58** [comment]
Thanks @louisifn. Keep sending stuff through guys.

**Comment by profjb58** [comment]
Ready to be merged. Made those smaller changes.

**Pull request merged**
