### PR TITLE
C26 messaging

### PR DESCRIPTION
**Pull request by nathanbillis**
Adding messaging, putting into PR so it can be reviewed because I'm not very happy with it, so would be great to hear feedback/people change it as needed. 

@profjb58 can you check this over for design issues

### CODE REVIEW

**Comment by nathanbillis** [comment]
> Could do with some text saying what each view represents. e.g. 'Recieved Messages' and 'Send to...'
> Some formatting issues when sending a message to another user with a large bar at the bottom of the screen.
> image
> Other than that, looks neet. I am getting a 'deleted_user' thing. If messages are kept after a user deletes an account this needs to be stated in the privacy statement or the users ability to access them needs to be prevented.
> image

understood. please can suggest ways to improve the design eg. where the placement of the text would look the best? thanks

**Comment by profjb58** [comment]
Placement of the Description for what each screen should be should be above all the users displayed at the top.

Best description would be
'Messages' - For the posts recieved. Figured this should be in quite a large font. Look a bit like spotifys headers.
'Send a Message' - Again at the top. Same font, 

image

As for the banner for each user, if possible and if they have a public account enabled as a boolean value might be good to include the about me section for there profile in a smaller font below the username just to fill the space out a bit.

**Comment by nathanbillis** [comment]
https://trello.com/c/ha2fppWA/46-c26-social-as-a-user-i-want-to-be-able-to-send-my-friends-messages-and-recipes-so-they-can-share-in-the-ones-i-enjoy 
- deleted users I think only shows when you delete an account using backend 
- The original plan was to add bio in the new message page and then the last recent message in the recent messages page, but I don't have time and it would be feature creep

**Comment by profjb58** [comment]
Sorry to be a pain Nathan. Was looking through again and spotted some other things.
The changes look great though.

image
Get a white bar on top when opening someones post.

Get a blank post sometimes.
image
Not sure why this happens.

**Comment by nathanbillis** [comment]
White bar don’t know how to fix without a full rewrite. Don’t know how to
debug blank posts

**Comment by profjb58** [comment]
Also, another bug I found is this thing.

image
When you post to someone and then return back to the recent posts page you get this design error. It returns back to normal when entering the recent posts page again.

**Comment by profjb58** [comment]
> Also, another bug I found is this thing.
> 
> image
> When you post to someone and then return back to the recent posts page you get this design error. It returns back to normal when entering the recent posts page again.

If your short on time, i'm guessing this bug would be the priority and is the only that definitely needs to be fixed before handing over.

**Pull request merged**
