### PR TITLE
A4 A11 user profile (tests) + Beginning of A10 (Kudos, formerly Chef stars)

### PR DESCRIPTION
**Pull request by profjb58**
**IMPORTANT: Update requires a re-register. I tried everything to not have to do this but we had redundant variables we didn't need in UserInfoPrivate.**

All user profile stuff is now complete.

**Added**
- A bunch of new tests. Info available in Test report.
- Kudos system
- Private/Public profile visibility tabs and functionality

**Fixed**
- Private/public profiles privacy data now sync correctly.
- Massive Intent issue. Meant wrong data was being sent out. Created a deepClone() method to prevent passing by reference to create a new temporary UserInfoPrivate object before saving.
- Images uploading before the user has pressed save. Now includes a progress bar + dialogs for if the image upload hasn't finished.

**Removed**
- Redundant code/comments
- Redundant variables in UserInfoPrivate.

p.s. added louis as an extra reviewer to test he is happy with the new private/public privacy stuff.

### CODE REVIEW

**Comment by profjb58** [comment]
Image uploads do not update and public profile no longer displays the profile image.
This is an issue with a rebase that hasn't worked properly because it worked prior.

**Comment by profjb58** [comment]
Because the image upload issue exists there might be other issues that have arisen since the rebase that need to be looked at.

**Comment by profjb58** [comment]
Well i'm a dope. Had it so my image wasn't being displayed in the privacy settings so I thought uploads where broken. Soz Nathan, re-requested a review but you don't need to re-review. Unless u want to :P.

**Comment by nathanbillis** [comment]
Approved by both @jamesclawley and @louisifn via Slack

**Pull request merged**
