### PR TITLE
User searching

### PR DESCRIPTION
**Pull request by nathanbillis**
User Searching now works :)

### CODE REVIEW

**Comment by nathanbillis** [comment]
Include @louisifn profile fix

**Comment by nathanbillis** [comment]
ready for review :)

**Comment by nathanbillis** [comment]
[User Searching - Extending searching to allow searching of user profiles](https://trello.com/c/kyZlnlwH/71-user-searching-extending-searching-to-allow-searching-of-user-profiles)

**Comment by profjb58** [comment]
Apologies, got another bug, this ones a bit more serious.
#108 
This is a long standing issue previously thought to be down to Algolia. It isn't to do with this branch specifically but should be fixed anyway since this is the last pull request for searching.

**Pull request merged**
