### PR TITLE
A4 user profiles

### PR DESCRIPTION
**Pull request by profjb58**
Finished user profiles A4 + all Unit tests & Espresso tests.

Going to take a while to figure out what to merge into master without breaking it. 
A lot of stuff has changed. E.g. MainActivity, Login, preferences and UserInfo classes have all been edited for this story.
You can check the tests for the time being though, they should all work but might be worth testing on different devices.

### CODE REVIEW

**Comment by profjb58** [comment]
Just a heads up. This branch has some remnants of an incomplete A11 task. Might need to make a seperate branch. There isn't really anything implemented for A11 other than the UI though so it wont cause conflicts.

**Comment by profjb58** [comment]
Might be helpful if @nathanbillis  or @jamesclawley are free to check through why the Travis build is failing as well. Already spent waaay to long on this :P.

**Comment by nathanbillis** [comment]
``` java
Process: com.group4sweng.scranplan, PID: 6567
    java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
        at com.group4sweng.scranplan.UserInfo.UserInfoPrivate.<init>(UserInfoPrivate.java:42)
        at com.group4sweng.scranplan.MainActivity$1$1.onComplete(MainActivity.java:128)
        at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by nathanbillis** [comment]
@profjb58 I get the above error when trying to launch the app, even after installation etc.

**Pull request merged**
