### PR TITLE
Fix #113 and #108

### LINKED ISSUE #108: Switching between Tabs breaks searching
How to reproduce:
- Switch to the Mealplanner or Feed screens.
- Return back to the Recipes screen and attempt to search
- Should come up with a blank search result.

Search results will fail consistently afterwards as well regardless.
This was previously thought to be an issue with Algolia but dosen't seem to be. It's a very well hidden issue which is why it's took a while to figure out.

searching fail

### LINKED ISSUE #113: filtering breaking searching by chef
Linked from issue #111, only looking at filters and searching by chef.

### PR DESCRIPTION
**Pull request by nathanbillis**
Fixes the two searching bugs :) - fix #113 and fix #108

### CODE REVIEW

**Comment by profjb58** [comment]
Filtering still breaks searching for a chef. For e.g. I couldn't search for Louis profile 'scranners' when I had a filter enabled but when going back and disabling all filters I could.

#108 however is fixed.

**Comment by nathanbillis** [comment]
> Filtering still breaks searching for a chef. For e.g. I couldn't search for Louis profile 'scranners' when I had a filter enabled but when going back and disabling all filters I could.
What do you get? a blank screen or the recipes populating or no results found dialogue?

**Comment by nathanbillis** [comment]
Please can you let me know exactly the steps needed because I've enabled all the stuff and don't get those issues

**Comment by profjb58** [comment]
specific conditions

**Comment by profjb58** [comment]
Yep that fixed it, decent.

**Comment by nathanbillis** [comment]
> Yep that fixed it, decent.

is that approval 😉

**Comment by nathanbillis** [comment]
> > Yep that fixed it, decent.
> 
> is that approval 😉

@profjb58

**Pull request merged**
