### PR TITLE
changes onResume in home - shared preferences was now working

### PR DESCRIPTION
**Pull request by louisifn**
getSharedPreferences no longer used - not sure if these were ever working? loadSearchOptions() is now never called and storeSearchOptions() & resetFilters() seem to only be used in tests?

### CODE REVIEW

**Comment by profjb58** [comment]
? The shared preferences is a fix I added for when search options reset when going to an activity. They should work.

**Comment by louisifn** [comment]
#155 fix

**Comment by profjb58** [comment]
Removing shared preferences will re-introduce the bug whereby filters reset so it's worth keeping them and figuring out why they are not working.

**Comment by profjb58** [comment]
Yeah i've tested on the main branch, It all seems to work.

**Comment by profjb58** [comment]
From Becky. remove translucency for create recipe button.

**Pull request merged**
