### PR TITLE
C28, C16, CC31, C29 and C24 Social stories

### PR DESCRIPTION
**Pull request by louisifn**
Social stories ready for peer review. Both Expresso and manual testing complete with a testing report on the drive. Due to a recent merge with the master, should merge reasonably well.

Have also added reviewing capabilities from recipe info page that populate and operate in the same manner.

### CODE REVIEW

**Comment by louisifn** [comment]
Ah sorry boss, let me know if I can help

**Comment by profjb58** [comment]
Linked to #92

**Comment by profjb58** [comment]
> 
> 
> This is why I'm afraid of the profile settings...

Yeah it's a bit of a behemoth. I suppose it's 5 user stories. Was always gonna be a tricky pull request :P.

**Comment by profjb58** [comment]
Also a thing to note. The public profile loads differently depending on if it's loading a local user (IE it'self) or someone elses profile. This is to conserve memory, queries etc...

Checking anothers users profile therefore is very likely to fail unless this is accounted for.
Given the amount of time already put in that might be something I could work on after exams/coursework etc...

**Comment by louisifn** [comment]
Is this ready to go through yet?

**Comment by nathanbillis** [comment]
@profjb58 what changes are you requesting?

**Comment by louisifn** [comment]
Think the main changes he wants come with the follow/unfollow shindig, but he wants them to work with searching for a user and viewing another user profile. I need to work with you with angolia when we do the follow/unfollow and may need to change the way viewing a profile operates but the point I'm attempting to get to is these changes are going to come in the next story.

**Pull request merged**
