### PR TITLE
Jp bug fixing

### PR DESCRIPTION
**Pull request by Jimb0nda**
Fixed deleting review problem

Altered info screen layout, Title shouldn't impact the buttons at the top

Fixed review duplication problem and image upload problem

### CODE REVIEW

**Comment by nathanbillis** [comment]
Do you know if this closes any issues that are open?

**Comment by Jimb0nda** [comment]
> Do you know if this closes any issues that are open?

If i new where to find things on here i would tell you what they are mate.

There should be the review delete one and the recipe info screen layout issue

**Comment by Jimb0nda** [comment]
103 and 105

**Comment by nathanbillis** [comment]
Thanks :)

**Pull request merged**
